### ISSUE TITLE
Harmattan latin glyphs are not the same size as Andika

### ISSUE THREAD

**Issue by nim-nim** [silnrsi/font-harmattan#1]
Harmattan reuses Andika glyphs, which is nice, but it also resizes them.
The end result is writing documents that mix Harmattan and Andika (because Andika has progressed since its import in Harmattan) is challenging.

Please keep the sizing of the common latin glyphs in all sil fonts coordinated.

**Comment by LornaSIL** [comment]
Thanks for your feedback. Our desire is that if the Latin glyphs in Harmattan are used with the Arabic script that they fit nicely together. That is why the Latin glyphs in Harmattan were resized. That way people do not have to change fonts. If we were to leave them the same size then people would have to change the point size of the Latin glyphs for them to look nice with the Arabic glyphs.

**Comment by nim-nim** [comment]
@LornaSIL I understand why you chose to do it but the system breaks down once people start using the font in multilingual documents, where the latin Harmattan is not sufficient (because, for example, missing styles), and clashes in size with other latin text.

I grew up in a multilingual family, with early DTP systems. There was nothing I hated more than systems that assumed the only legitimate combination was full non-latin text, or non-latin-text + latin reduced to English needs.

People that do not use Latin script can get globalized too. globalization is more than English + other script

**Comment by nim-nim** [comment]
(and if I can: at least early systems tried to cram multiple scripts in a 8 bit encoding, so they suffered from severe glyphs scarcity, that's not a constrain on modern i18n fonts)

**Comment by LornaSIL** [comment]
I believe I understand you, but this font is primarily for Arabic script use. We've provided Latin script characters as a convenience for Arabic script users when they want to throw a little Latin in there, not for major use of Latin script. Even the Latin digits are sized for those languages that use Latin-style digits with the Arabic script (most African languages that use Arabic script). We don't include a wide range of special Latin characters because that is what our Latin fonts were designed for.

**Comment by nim-nim** [comment]
Yes, I also understand that. However, because this small limited convenience Latin is scaled, it will clash with more complete versions of Andika, and ends up as an inconvenience. It would not be a problem if it used the same sizing

**Comment by LornaSIL** [comment]
I'm sorry, but our clients for this particular font are Arabic script users and this is the desired behavior for the font.

**Comment by bobh0303** [comment]
@nim-nim What is compelling you to use the Latin glyphs that are in Harmattan? You say the character coverage is insufficient for your needs anyway, so it sounds to me like you should just always use the latest Andika wherever you need Latin script.

**Comment by jvgaultney** [comment]
Whenever you mix two scripts that are unrelated you face sizing problems. There is always a primary script that sets the 'normal' size of the font - in this case Arabic. Then any secondary scripts also supported by the font (in this case Latin) need to be sized in relation to how text in that script ought to appear in the context of the primary script. For a variety of design reasons that means that Latin glyphs in many Arabic fonts need to be reduced to balance properly. 

Even in the most coordinated multiscript project in the world (Noto) the sizing is sometimes problematic for this reason.  You can't assume that Noto Latin will look properly sized alongside Noto for other scripts, even though they've taken great care to make the various script fonts semi-compatible.

**Comment by nim-nim** [comment]
@bobh0303 whenever a latin text run does not end precisely on Andika/Harmattan boundary, you get odd differences in size for the latin letters (and of course for Greek and Cyrillic, since *their* sizing is coordinated with latin)

**Comment by bobh0303** [comment]
> whenever a latin text run does not end precisely on Andika/Harmattan boundary, you get odd differences in size for the latin letters

Real life examples please.
