### ISSUE TITLE
FTML files missing required <head> element

### ISSUE THREAD

**Issue by mhosken** [silnrsi/font-harmattan#2]
The FTML spec states that the <head> element is a required element of a file and is missing from a number of .ftml files in tests/

**Comment by bobh0303** [comment]
Which ones, please? I don't see any:
```
vagrant@smith-bionic:/smith/font-harmattan/tests$ grep -rL '<head' *.ftml
vagrant@smith-bionic:/smith/font-harmattan/tests$
```

**Comment by bobh0303** [comment]
The problem was element ordering -- head element was present but was after testgroup. 

As of 34f474a202f1 all ftml files now validate against current DTD.
